services:
#    release.example:
#        class: Kishron\ReleaseBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    HipChat:
        class: Kishron\ReleaseBundle\Services\HipChatConnect
        arguments: ["@service_container"]

    Rally:
        class: Kishron\ReleaseBundle\Services\RallyConnect
        arguments: ["@service_container"]
        
    Zendesk:
        class: Kishron\ReleaseBundle\Services\ZendeskConnect
        arguments: ["@service_container"]