services:
#    release.example:
#        class: Kishron\ReleaseBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    HipChat:
        class: Kishron\ReleaseBundle\Services\HipChatConnect

    Rally:
        class: Kishron\ReleaseBundle\Services\RallyConnect