<?php

namespace Kishron\ReleaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReleaseObjRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleaseObjRepository extends EntityRepository
{
}
