<?php

namespace Kishron\ReleaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevisionRepository extends EntityRepository
{
    public function getRevisionsByRelease($releaseId) {
        $em = $this->getEntityManager();
        $query = $em->getRepository('ReleaseBundle:Revision')
                ->createQueryBuilder('r')
                ->select('r')
                ->innerJoin('r.story', 's')
                ->innerJoin('r.dataCenter', 'dc')
                ->innerJoin('s.release', 'release')
                ->where('release = :releaseId')
                ->setParameter('releaseId', $releaseId)
                ->getQuery();
        $products = $query->getResult();
        return $products;
    }
}
