<?php

namespace Kishron\ReleaseBundle\Repository;

/**
 * UserReleaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReleaseRepository extends \Doctrine\ORM\EntityRepository
{
}
